// ============================================================
// Nepal Heritage Trails — In-Memory Data Store
// Rich seed data representing authentic Nepali tourism experiences
// ============================================================

const { v4: uuidv4 } = require('uuid');

// ============================================================
// USERS
// ============================================================
const users = [
  {
    id: 'u1-tourist-001',
    email: 'sarah.chen@email.com',
    password_hash: '$2b$10$mockhashedpassword1',
    full_name: 'Sarah Chen',
    role: 'tourist',
    avatar_url: null,
    phone: '+1-555-0123',
    bio: 'Adventure traveler and cultural enthusiast from San Francisco.',
    location: 'San Francisco, USA',
    is_verified: true,
    is_active: true,
    created_at: '2024-01-15T08:00:00Z'
  },
  {
    id: 'u2-provider-001',
    email: 'ram.gurung@email.com',
    password_hash: '$2b$10$mockhashedpassword2',
    full_name: 'Ram Bahadur Gurung',
    role: 'provider',
    avatar_url: null,
    phone: '+977-9841234567',
    bio: 'Born and raised in Ghandruk. 15 years experience as a mountain guide and homestay host.',
    location: 'Ghandruk, Kaski',
    is_verified: true,
    is_active: true,
    created_at: '2023-06-10T05:30:00Z'
  },
  {
    id: 'u3-provider-002',
    email: 'sita.thapa@email.com',
    password_hash: '$2b$10$mockhashedpassword3',
    full_name: 'Sita Thapa',
    role: 'provider',
    avatar_url: null,
    phone: '+977-9851234567',
    bio: 'Master Thangka painter and cultural heritage guide from Bhaktapur.',
    location: 'Bhaktapur, Bagmati',
    is_verified: true,
    is_active: true,
    created_at: '2023-08-20T06:00:00Z'
  },
  {
    id: 'u4-provider-003',
    email: 'dorje.sherpa@email.com',
    password_hash: '$2b$10$mockhashedpassword4',
    full_name: 'Dorje Sherpa',
    role: 'provider',
    avatar_url: null,
    phone: '+977-9861234567',
    bio: 'Sherpa mountaineer from Namche Bazaar. Summited Everest 3 times. Passionate about sustainable tourism.',
    location: 'Namche Bazaar, Solukhumbu',
    is_verified: true,
    is_active: true,
    created_at: '2023-03-15T04:45:00Z'
  },
  {
    id: 'u5-admin-001',
    email: 'admin@nepalheritagetrails.com',
    password_hash: '$2b$10$mockhashedpassword5',
    full_name: 'Nepal Heritage Admin',
    role: 'admin',
    avatar_url: null,
    phone: '+977-1-4000000',
    bio: 'Platform administrator',
    location: 'Kathmandu, Nepal',
    is_verified: true,
    is_active: true,
    created_at: '2023-01-01T00:00:00Z'
  }
];

// ============================================================
// EXPERIENCES
// ============================================================
const experiences = [
  {
    id: 'exp-001',
    provider_id: 'u2-provider-001',
    title: 'Ghandruk Gurung Homestay Experience',
    slug: 'ghandruk-gurung-homestay',
    description: 'Immerse yourself in traditional Gurung culture in the picturesque village of Ghandruk. Wake up to panoramic views of Annapurna South and Machhapuchhre (Fishtail). Stay with a local Gurung family, enjoy authentic dal-bhat cooked on a wood fire, learn traditional songs and dances, and trek through rhododendron forests. This is not just accommodation — it is a doorway into centuries-old mountain culture.',
    short_description: 'Stay with a Gurung family in Ghandruk with panoramic Annapurna views and authentic cultural immersion.',
    category: 'homestay',
    price_per_person: 3500,
    currency: 'NPR',
    duration_hours: 48,
    max_guests: 6,
    location_name: 'Ghandruk, Kaski District',
    latitude: 28.3716,
    longitude: 83.8017,
    district: 'Kaski',
    province: 'Gandaki',
    images: ['/images/ghandruk-1.jpg', '/images/ghandruk-2.jpg', '/images/ghandruk-3.jpg'],
    amenities: ['Traditional meals', 'Mountain views', 'Cultural program', 'Guided village walk', 'Hot shower'],
    languages: ['Nepali', 'English', 'Gurung'],
    is_verified: true,
    avg_rating: 4.8,
    total_reviews: 124,
    total_bookings: 340,
    community_impact_score: 9.2,
    created_at: '2023-07-01T06:00:00Z'
  },
  {
    id: 'exp-002',
    provider_id: 'u3-provider-002',
    title: 'Bhaktapur Thangka Painting Workshop',
    slug: 'bhaktapur-thangka-workshop',
    description: 'Learn the sacred art of Thangka painting from master artist Sita Thapa in her ancestral workshop in Bhaktapur Durbar Square. Discover the spiritual symbolism behind each brushstroke, prepare natural mineral pigments, and create your own miniature Thangka to take home. Includes a guided tour of Bhaktapur\'s ancient art galleries and a traditional Newari lunch.',
    short_description: 'Master the ancient art of Thangka painting with a master artist in Bhaktapur Durbar Square.',
    category: 'workshop',
    price_per_person: 5500,
    currency: 'NPR',
    duration_hours: 8,
    max_guests: 8,
    location_name: 'Bhaktapur Durbar Square',
    latitude: 27.6722,
    longitude: 85.4298,
    district: 'Bhaktapur',
    province: 'Bagmati',
    images: ['/images/thangka-1.jpg', '/images/thangka-2.jpg'],
    amenities: ['Art materials provided', 'Newari lunch', 'Gallery tour', 'Take-home artwork', 'Certificate'],
    languages: ['Nepali', 'English', 'Newari'],
    is_verified: true,
    avg_rating: 4.9,
    total_reviews: 87,
    total_bookings: 210,
    community_impact_score: 8.8,
    created_at: '2023-08-25T06:00:00Z'
  },
  {
    id: 'exp-003',
    provider_id: 'u4-provider-003',
    title: 'Everest Base Camp Trek with Sherpa Guide',
    slug: 'everest-base-camp-sherpa-guide',
    description: 'Trek to the foot of the world\'s highest peak with Dorje Sherpa, a three-time Everest summiter. This 14-day guided experience takes you through Sherpa villages, ancient monasteries, and breathtaking Himalayan landscapes. Learn about Sherpa culture, Buddhist traditions, and mountaineering history from someone who lives it every day.',
    short_description: 'Trek to Everest Base Camp with a 3x Everest summiter and Sherpa cultural guide.',
    category: 'guide',
    price_per_person: 85000,
    currency: 'NPR',
    duration_hours: 336,
    max_guests: 12,
    location_name: 'Namche Bazaar to Everest Base Camp',
    latitude: 27.9881,
    longitude: 86.8250,
    district: 'Solukhumbu',
    province: 'Province 1',
    images: ['/images/ebc-1.jpg', '/images/ebc-2.jpg', '/images/ebc-3.jpg'],
    amenities: ['Experienced guide', 'Porter support', 'Teahouse accommodation', 'Meals included', 'Permit assistance'],
    languages: ['Nepali', 'English', 'Sherpa'],
    is_verified: true,
    avg_rating: 5.0,
    total_reviews: 56,
    total_bookings: 120,
    community_impact_score: 9.5,
    created_at: '2023-04-01T05:00:00Z'
  },
  {
    id: 'exp-004',
    provider_id: 'u3-provider-002',
    title: 'Patan Durbar Square Heritage Walk',
    slug: 'patan-heritage-walk',
    description: 'Explore the UNESCO World Heritage Site of Patan Durbar Square with an expert heritage guide. Discover ancient temples, intricate Newari wood carvings, the famous Krishna Mandir, and the Patan Museum. Visit working artisan workshops where traditional metalwork, woodcarving, and pottery techniques have been passed down for generations.',
    short_description: 'Guided heritage walk through Patan\'s UNESCO temples, artisan workshops, and ancient squares.',
    category: 'heritage_site',
    price_per_person: 2500,
    currency: 'NPR',
    duration_hours: 4,
    max_guests: 15,
    location_name: 'Patan Durbar Square, Lalitpur',
    latitude: 27.6727,
    longitude: 85.3252,
    district: 'Lalitpur',
    province: 'Bagmati',
    images: ['/images/patan-1.jpg', '/images/patan-2.jpg'],
    amenities: ['Expert guide', 'Museum entry', 'Artisan workshop visit', 'Cultural briefing', 'Refreshments'],
    languages: ['Nepali', 'English', 'Hindi', 'Newari'],
    is_verified: true,
    avg_rating: 4.7,
    total_reviews: 203,
    total_bookings: 580,
    community_impact_score: 8.5,
    created_at: '2023-09-10T06:00:00Z'
  },
  {
    id: 'exp-005',
    provider_id: 'u2-provider-001',
    title: 'Annapurna Sunrise Yoga & Meditation Retreat',
    slug: 'annapurna-yoga-meditation',
    description: 'A transformative 3-day retreat in the foothills of Annapurna, combining yoga, meditation, and Himalayan wellness traditions. Practice sunrise yoga with panoramic mountain views, learn Ayurvedic cooking, participate in singing bowl meditation, and hike to a sacred cave temple. Accommodation in an eco-lodge with organic farm-to-table meals.',
    short_description: 'Yoga and meditation retreat nestled in the Annapurna foothills with Himalayan wellness traditions.',
    category: 'homestay',
    price_per_person: 12000,
    currency: 'NPR',
    duration_hours: 72,
    max_guests: 10,
    location_name: 'Australian Camp, Kaski',
    latitude: 28.3340,
    longitude: 83.8145,
    district: 'Kaski',
    province: 'Gandaki',
    images: ['/images/yoga-1.jpg', '/images/yoga-2.jpg'],
    amenities: ['Yoga sessions', 'Meditation', 'Organic meals', 'Eco-lodge', 'Singing bowls', 'Nature hikes'],
    languages: ['Nepali', 'English'],
    is_verified: true,
    avg_rating: 4.9,
    total_reviews: 68,
    total_bookings: 190,
    community_impact_score: 9.0,
    created_at: '2023-10-01T05:30:00Z'
  },
  {
    id: 'exp-006',
    provider_id: 'u3-provider-002',
    title: 'Newari Cooking Class & Food Tour',
    slug: 'newari-cooking-food-tour',
    description: 'Discover the rich culinary heritage of the Newar people in this hands-on cooking class and food walking tour through Kathmandu\'s old streets. Learn to prepare traditional dishes like Wo (lentil pancake), Chatamari (Newari pizza), Yomari, and more. Visit local spice markets, hidden food stalls, and a traditional kitchen.',
    short_description: 'Hands-on Newari cooking class with a food walking tour through Kathmandu\'s ancient streets.',
    category: 'workshop',
    price_per_person: 4000,
    currency: 'NPR',
    duration_hours: 6,
    max_guests: 10,
    location_name: 'Asan, Kathmandu',
    latitude: 27.7080,
    longitude: 85.3118,
    district: 'Kathmandu',
    province: 'Bagmati',
    images: ['/images/food-1.jpg', '/images/food-2.jpg'],
    amenities: ['Cooking ingredients', 'Recipe booklet', 'Market tour', 'Full meal', 'Local guide'],
    languages: ['Nepali', 'English'],
    is_verified: true,
    avg_rating: 4.8,
    total_reviews: 156,
    total_bookings: 420,
    community_impact_score: 8.3,
    created_at: '2023-11-05T06:00:00Z'
  },
  {
    id: 'exp-007',
    provider_id: 'u4-provider-003',
    title: 'Langtang Valley Cultural Trek',
    slug: 'langtang-valley-trek',
    description: 'A 7-day trek through the Langtang Valley — known as the valley of glaciers. Walk through Tamang villages rebuilt after the 2015 earthquake, visit ancient gompas, taste yak cheese at the world\'s highest cheese factory, and witness the resilience of mountain communities firsthand. This trek directly supports earthquake recovery efforts.',
    short_description: 'Trek through the Langtang Valley visiting Tamang villages and supporting earthquake recovery.',
    category: 'guide',
    price_per_person: 45000,
    currency: 'NPR',
    duration_hours: 168,
    max_guests: 10,
    location_name: 'Langtang National Park',
    latitude: 28.2139,
    longitude: 85.5200,
    district: 'Rasuwa',
    province: 'Bagmati',
    images: ['/images/langtang-1.jpg', '/images/langtang-2.jpg'],
    amenities: ['Experienced guide', 'Porter support', 'Permits', 'Teahouse stays', 'Meals included'],
    languages: ['Nepali', 'English', 'Tamang'],
    is_verified: true,
    avg_rating: 4.7,
    total_reviews: 42,
    total_bookings: 95,
    community_impact_score: 9.8,
    created_at: '2023-05-15T05:00:00Z'
  },
  {
    id: 'exp-008',
    provider_id: 'u2-provider-001',
    title: 'Pokhara Lakeside Kayaking & Village Experience',
    slug: 'pokhara-kayaking-village',
    description: 'Paddle across the serene Phewa Lake with views of the Annapurna range reflected in its waters. After kayaking, visit a lakeside fishing village, learn traditional net-casting techniques, and enjoy a fresh fish lunch prepared by local families. End the day with a peaceful boat ride to the Tal Barahi Temple island.',
    short_description: 'Kayak on Phewa Lake, visit a fishing village, and explore Pokhara\'s natural beauty.',
    category: 'guide',
    price_per_person: 3000,
    currency: 'NPR',
    duration_hours: 6,
    max_guests: 8,
    location_name: 'Phewa Lake, Pokhara',
    latitude: 28.2096,
    longitude: 83.9563,
    district: 'Kaski',
    province: 'Gandaki',
    images: ['/images/pokhara-1.jpg', '/images/pokhara-2.jpg'],
    amenities: ['Kayak gear', 'Life jacket', 'Fish lunch', 'Village tour', 'Temple visit'],
    languages: ['Nepali', 'English'],
    is_verified: true,
    avg_rating: 4.6,
    total_reviews: 92,
    total_bookings: 310,
    community_impact_score: 7.5,
    created_at: '2023-12-01T06:00:00Z'
  },
  {
    id: 'exp-009',
    provider_id: 'u3-provider-002',
    title: 'Bhaktapur Pottery & Ceramics Workshop',
    slug: 'bhaktapur-pottery-workshop',
    description: 'Get your hands dirty at Pottery Square in Bhaktapur, where families have been shaping clay for over 800 years. Learn traditional wheel-throwing and hand-building techniques from a multigenerational potter family. Create your own piece, learn about the cultural significance of Newari pottery, and explore the atmospheric square lined with drying pots.',
    short_description: 'Learn 800-year-old pottery techniques at Bhaktapur\'s iconic Pottery Square.',
    category: 'workshop',
    price_per_person: 3500,
    currency: 'NPR',
    duration_hours: 5,
    max_guests: 8,
    location_name: 'Pottery Square, Bhaktapur',
    latitude: 27.6710,
    longitude: 85.4292,
    district: 'Bhaktapur',
    province: 'Bagmati',
    images: ['/images/pottery-1.jpg', '/images/pottery-2.jpg'],
    amenities: ['Clay materials', 'Expert instruction', 'Take-home pottery', 'Traditional tea', 'Cultural tour'],
    languages: ['Nepali', 'English', 'Newari'],
    is_verified: true,
    avg_rating: 4.7,
    total_reviews: 78,
    total_bookings: 200,
    community_impact_score: 8.6,
    created_at: '2024-01-10T06:00:00Z'
  },
  {
    id: 'exp-010',
    provider_id: 'u4-provider-003',
    title: 'Lumbini Buddhist Pilgrimage Tour',
    slug: 'lumbini-buddhist-pilgrimage',
    description: 'Visit the birthplace of Lord Buddha in Lumbini, a UNESCO World Heritage Site. Explore the sacred garden, Maya Devi Temple, the Ashoka Pillar, and monasteries built by Buddhist nations from around the world. Includes meditation sessions with resident monks, a peace pagoda visit, and insights into the history and philosophy of Buddhism.',
    short_description: 'Pilgrimage to Lumbini, the birthplace of Buddha, with guided monastery tours and meditation.',
    category: 'heritage_site',
    price_per_person: 6000,
    currency: 'NPR',
    duration_hours: 10,
    max_guests: 20,
    location_name: 'Lumbini Sacred Garden',
    latitude: 27.4833,
    longitude: 83.2767,
    district: 'Rupandehi',
    province: 'Lumbini',
    images: ['/images/lumbini-1.jpg', '/images/lumbini-2.jpg'],
    amenities: ['Expert Buddhist guide', 'Meditation session', 'Monastery visits', 'Lunch', 'Transport'],
    languages: ['Nepali', 'English', 'Hindi'],
    is_verified: true,
    avg_rating: 4.8,
    total_reviews: 145,
    total_bookings: 450,
    community_impact_score: 8.0,
    created_at: '2023-09-20T05:45:00Z'
  }
];

// ============================================================
// FEATURED TRAILS
// ============================================================
const trails = [
  {
    id: 'trail-001',
    creator_id: null,
    title: 'Kathmandu Valley Heritage Circuit',
    slug: 'kathmandu-heritage-circuit',
    description: 'A 5-day deep dive into the art, architecture, and living culture of the Kathmandu Valley. Explore three UNESCO Durbar Squares, master ancient crafts, savor Newari cuisine, and discover the spiritual heart of Nepal.',
    cover_image: '/images/trail-kathmandu.jpg',
    difficulty: 'easy',
    duration_days: 5,
    total_cost_estimate: 25000,
    currency: 'NPR',
    interests: ['Culture', 'Food', 'Spirituality'],
    travel_style: 'Cultural Explorer',
    is_featured: true,
    total_bookings: 230,
    avg_rating: 4.8,
    days: [
      { day_number: 1, title: 'Bhaktapur Durbar Square & Thangka Workshop', location: 'Bhaktapur', experience_id: 'exp-002', estimated_cost: 5500 },
      { day_number: 2, title: 'Patan Heritage Walk & Artisan Quarter', location: 'Patan, Lalitpur', experience_id: 'exp-004', estimated_cost: 2500 },
      { day_number: 3, title: 'Newari Cooking & Kathmandu Food Tour', location: 'Kathmandu', experience_id: 'exp-006', estimated_cost: 4000 },
      { day_number: 4, title: 'Pottery Workshop & Bhaktapur Back Streets', location: 'Bhaktapur', experience_id: 'exp-009', estimated_cost: 3500 },
      { day_number: 5, title: 'Swayambhunath & Boudhanath Stupas', location: 'Kathmandu', estimated_cost: 3000 }
    ]
  },
  {
    id: 'trail-002',
    creator_id: null,
    title: 'Annapurna Culture & Adventure Trail',
    slug: 'annapurna-culture-adventure',
    description: 'Combine breathtaking mountain scenery with authentic Gurung culture. Trek through rhododendron forests, stay in traditional homestays, practice sunrise yoga with Himalayan views, and kayak on Phewa Lake.',
    cover_image: '/images/trail-annapurna.jpg',
    difficulty: 'moderate',
    duration_days: 7,
    total_cost_estimate: 35000,
    currency: 'NPR',
    interests: ['Trekking', 'Culture', 'Adventure'],
    travel_style: 'Active Adventurer',
    is_featured: true,
    total_bookings: 180,
    avg_rating: 4.9,
    days: [
      { day_number: 1, title: 'Arrive in Pokhara & Lakeside Exploration', location: 'Pokhara', estimated_cost: 3000 },
      { day_number: 2, title: 'Kayaking & Fishing Village Experience', location: 'Phewa Lake', experience_id: 'exp-008', estimated_cost: 3000 },
      { day_number: 3, title: 'Trek to Australian Camp & Yoga Retreat', location: 'Australian Camp', experience_id: 'exp-005', estimated_cost: 6000 },
      { day_number: 4, title: 'Yoga, Meditation & Himalayan Wellness', location: 'Australian Camp', estimated_cost: 4000 },
      { day_number: 5, title: 'Trek to Ghandruk & Gurung Homestay', location: 'Ghandruk', experience_id: 'exp-001', estimated_cost: 3500 },
      { day_number: 6, title: 'Gurung Cultural Immersion & Village Life', location: 'Ghandruk', estimated_cost: 3000 },
      { day_number: 7, title: 'Sunrise over Annapurna & Return to Pokhara', location: 'Ghandruk to Pokhara', estimated_cost: 4000 }
    ]
  },
  {
    id: 'trail-003',
    creator_id: null,
    title: 'Sacred Nepal Spiritual Journey',
    slug: 'sacred-nepal-spiritual',
    description: 'A soul-stirring 6-day pilgrimage across Nepal\'s most sacred sites. From the birthplace of Buddha in Lumbini to the holy Hindu temples of Kathmandu, experience the spiritual tapestry that makes Nepal the land of gods.',
    cover_image: '/images/trail-spiritual.jpg',
    difficulty: 'easy',
    duration_days: 6,
    total_cost_estimate: 30000,
    currency: 'NPR',
    interests: ['Spirituality', 'Culture'],
    travel_style: 'Spiritual Seeker',
    is_featured: true,
    total_bookings: 150,
    avg_rating: 4.7,
    days: [
      { day_number: 1, title: 'Kathmandu - Pashupatinath & Boudhanath', location: 'Kathmandu', estimated_cost: 4000 },
      { day_number: 2, title: 'Patan Heritage & Golden Temple', location: 'Patan', experience_id: 'exp-004', estimated_cost: 2500 },
      { day_number: 3, title: 'Travel to Lumbini & Sacred Garden', location: 'Lumbini', experience_id: 'exp-010', estimated_cost: 8000 },
      { day_number: 4, title: 'Lumbini Monastery Tour & Meditation', location: 'Lumbini', estimated_cost: 4000 },
      { day_number: 5, title: 'Return to Pokhara & Peace Pagoda', location: 'Pokhara', estimated_cost: 5000 },
      { day_number: 6, title: 'Sunrise Yoga & Meditation Retreat', location: 'Pokhara', experience_id: 'exp-005', estimated_cost: 6000 }
    ]
  }
];

// ============================================================
// REVIEWS
// ============================================================
const reviews = [
  { id: 'rev-001', user_id: 'u1-tourist-001', experience_id: 'exp-001', rating: 5, title: 'Life-changing experience!', comment: 'Staying with Ram\'s family in Ghandruk was the highlight of my Nepal trip. The views of Machhapuchhre at sunrise were absolutely breathtaking. The dal-bhat was the best I had in all of Nepal. Highly recommend!', created_at: '2024-01-20T08:00:00Z' },
  { id: 'rev-002', user_id: 'u1-tourist-001', experience_id: 'exp-002', rating: 5, title: 'Beautiful art, beautiful soul', comment: 'Sita is an incredible artist and teacher. I had no painting experience but she guided me patiently. The Newari lunch was delicious and the workshop setting in Bhaktapur is magical.', created_at: '2024-01-22T10:00:00Z' },
  { id: 'rev-003', user_id: 'u1-tourist-001', experience_id: 'exp-003', rating: 5, title: 'Once in a lifetime trek', comment: 'Dorje is the best guide you could ask for. His knowledge of the mountains and Sherpa culture is incredible. He made sure everyone was safe and comfortable throughout the trek. Seeing Everest up close is something I\'ll never forget.', created_at: '2024-02-05T07:00:00Z' },
  { id: 'rev-004', user_id: 'u1-tourist-001', experience_id: 'exp-006', rating: 5, title: 'Delicious and fun!', comment: 'The Newari cooking class was so much fun! We visited Asan market, learned to make traditional dishes, and ate like kings. The food walking tour afterwards was the cherry on top.', created_at: '2024-01-25T12:00:00Z' },
  { id: 'rev-005', user_id: 'u1-tourist-001', experience_id: 'exp-004', rating: 4, title: 'Amazing heritage', comment: 'The Patan Durbar Square walk was fascinating. Our guide\'s knowledge of Newari architecture and history was incredible. Only giving 4 stars because we felt a bit rushed at the museum.', created_at: '2024-01-23T14:00:00Z' }
];

// ============================================================
// COMMUNITY IMPACT
// ============================================================
const impactStats = {
  families_supported: 1247,
  total_revenue_generated: 45200000,
  community_share_percentage: 72,
  cultural_programs_funded: 34,
  artisans_employed: 389,
  heritage_sites_maintained: 12,
  districts_reached: 28,
  travelers_served: 8940,
  distribution: [
    { category: 'Homestay Families', percentage: 35, amount: 15820000 },
    { category: 'Local Guides', percentage: 25, amount: 11300000 },
    { category: 'Artisan Workshops', percentage: 20, amount: 9040000 },
    { category: 'Heritage Preservation', percentage: 12, amount: 5424000 },
    { category: 'Community Education', percentage: 8, amount: 3616000 }
  ],
  regional: [
    { district: 'Kaski', families: 280, revenue: 9800000 },
    { district: 'Bhaktapur', families: 195, revenue: 7200000 },
    { district: 'Solukhumbu', families: 165, revenue: 8500000 },
    { district: 'Lalitpur', families: 150, revenue: 5400000 },
    { district: 'Kathmandu', families: 180, revenue: 6300000 },
    { district: 'Rasuwa', families: 95, revenue: 3200000 },
    { district: 'Rupandehi', families: 82, revenue: 2800000 },
    { district: 'Others', families: 100, revenue: 2000000 }
  ]
};

// ============================================================
// BOOKINGS
// ============================================================
const bookings = [
  {
    id: 'book-001',
    user_id: 'u1-tourist-001',
    experience_id: 'exp-001',
    booking_date: '2024-03-15',
    num_guests: 2,
    total_amount: 7000,
    status: 'confirmed',
    created_at: '2024-02-20T10:00:00Z'
  },
  {
    id: 'book-002',
    user_id: 'u1-tourist-001',
    experience_id: 'exp-006',
    booking_date: '2024-03-18',
    num_guests: 2,
    total_amount: 8000,
    status: 'completed',
    created_at: '2024-02-20T10:30:00Z'
  }
];

module.exports = { users, experiences, trails, reviews, impactStats, bookings };
