// ============================================================
// Fallback Data — Used when backend is not running
// ============================================================

export const fallbackExperiences = [
    {
        id: "exp-001",
        title: "Ghandruk Gurung Homestay Experience",
        slug: "ghandruk-gurung-homestay",
        short_description: "Stay with a Gurung family in Ghandruk with panoramic Annapurna views and authentic cultural immersion.",
        category: "homestay",
        price_per_person: 3500,
        currency: "NPR",
        duration_hours: 48,
        location_name: "Ghandruk, Kaski District",
        district: "Kaski",
        is_verified: true,
        avg_rating: 4.8,
        total_reviews: 124,
        total_bookings: 340,
        community_impact_score: 9.2,
        amenities: ["Traditional meals", "Mountain views", "Cultural program", "Guided village walk", "Hot shower"],
        languages: ["Nepali", "English", "Gurung"],
    },
    {
        id: "exp-002",
        title: "Bhaktapur Thangka Painting Workshop",
        slug: "bhaktapur-thangka-workshop",
        short_description: "Master the ancient art of Thangka painting with a master artist in Bhaktapur Durbar Square.",
        category: "workshop",
        price_per_person: 5500,
        currency: "NPR",
        duration_hours: 8,
        location_name: "Bhaktapur Durbar Square",
        district: "Bhaktapur",
        is_verified: true,
        avg_rating: 4.9,
        total_reviews: 87,
        total_bookings: 210,
        community_impact_score: 8.8,
        amenities: ["Art materials provided", "Newari lunch", "Gallery tour", "Take-home artwork", "Certificate"],
        languages: ["Nepali", "English", "Newari"],
    },
    {
        id: "exp-003",
        title: "Everest Base Camp Trek with Sherpa Guide",
        slug: "everest-base-camp-sherpa-guide",
        short_description: "Trek to Everest Base Camp with a 3x Everest summiter and Sherpa cultural guide.",
        category: "guide",
        price_per_person: 85000,
        currency: "NPR",
        duration_hours: 336,
        location_name: "Namche Bazaar to Everest Base Camp",
        district: "Solukhumbu",
        is_verified: true,
        avg_rating: 5.0,
        total_reviews: 56,
        total_bookings: 120,
        community_impact_score: 9.5,
        amenities: ["Experienced guide", "Porter support", "Teahouse accommodation", "Meals included", "Permit assistance"],
        languages: ["Nepali", "English", "Sherpa"],
    },
    {
        id: "exp-004",
        title: "Patan Durbar Square Heritage Walk",
        slug: "patan-heritage-walk",
        short_description: "Guided heritage walk through Patan's UNESCO temples, artisan workshops, and ancient squares.",
        category: "heritage_site",
        price_per_person: 2500,
        currency: "NPR",
        duration_hours: 4,
        location_name: "Patan Durbar Square, Lalitpur",
        district: "Lalitpur",
        is_verified: true,
        avg_rating: 4.7,
        total_reviews: 203,
        total_bookings: 580,
        community_impact_score: 8.5,
        amenities: ["Expert guide", "Museum entry", "Artisan workshop visit", "Cultural briefing", "Refreshments"],
        languages: ["Nepali", "English", "Hindi", "Newari"],
    },
    {
        id: "exp-005",
        title: "Annapurna Sunrise Yoga & Meditation Retreat",
        slug: "annapurna-yoga-meditation",
        short_description: "Yoga and meditation retreat nestled in the Annapurna foothills with Himalayan wellness traditions.",
        category: "homestay",
        price_per_person: 12000,
        currency: "NPR",
        duration_hours: 72,
        location_name: "Australian Camp, Kaski",
        district: "Kaski",
        is_verified: true,
        avg_rating: 4.9,
        total_reviews: 68,
        total_bookings: 190,
        community_impact_score: 9.0,
        amenities: ["Yoga sessions", "Meditation", "Organic meals", "Eco-lodge", "Singing bowls"],
        languages: ["Nepali", "English"],
    },
    {
        id: "exp-006",
        title: "Newari Cooking Class & Food Tour",
        slug: "newari-cooking-food-tour",
        short_description: "Hands-on Newari cooking class with a food walking tour through Kathmandu's ancient streets.",
        category: "workshop",
        price_per_person: 4000,
        currency: "NPR",
        duration_hours: 6,
        location_name: "Asan, Kathmandu",
        district: "Kathmandu",
        is_verified: true,
        avg_rating: 4.8,
        total_reviews: 156,
        total_bookings: 420,
        community_impact_score: 8.3,
        amenities: ["Cooking ingredients", "Recipe booklet", "Market tour", "Full meal", "Local guide"],
        languages: ["Nepali", "English"],
    },
    {
        id: "exp-007",
        title: "Langtang Valley Cultural Trek",
        slug: "langtang-valley-trek",
        short_description: "Trek through the Langtang Valley visiting Tamang villages and supporting earthquake recovery.",
        category: "guide",
        price_per_person: 45000,
        currency: "NPR",
        duration_hours: 168,
        location_name: "Langtang National Park",
        district: "Rasuwa",
        is_verified: true,
        avg_rating: 4.7,
        total_reviews: 42,
        total_bookings: 95,
        community_impact_score: 9.8,
        amenities: ["Experienced guide", "Porter support", "Permits", "Teahouse stays", "Meals included"],
        languages: ["Nepali", "English", "Tamang"],
    },
    {
        id: "exp-008",
        title: "Pokhara Lakeside Kayaking & Village Experience",
        slug: "pokhara-kayaking-village",
        short_description: "Kayak on Phewa Lake, visit a fishing village, and explore Pokhara's natural beauty.",
        category: "guide",
        price_per_person: 3000,
        currency: "NPR",
        duration_hours: 6,
        location_name: "Phewa Lake, Pokhara",
        district: "Kaski",
        is_verified: true,
        avg_rating: 4.6,
        total_reviews: 92,
        total_bookings: 310,
        community_impact_score: 7.5,
        amenities: ["Kayak gear", "Life jacket", "Fish lunch", "Village tour", "Temple visit"],
        languages: ["Nepali", "English"],
    },
    {
        id: "exp-009",
        title: "Bhaktapur Pottery & Ceramics Workshop",
        slug: "bhaktapur-pottery-workshop",
        short_description: "Learn 800-year-old pottery techniques at Bhaktapur's iconic Pottery Square.",
        category: "workshop",
        price_per_person: 3500,
        currency: "NPR",
        duration_hours: 5,
        location_name: "Pottery Square, Bhaktapur",
        district: "Bhaktapur",
        is_verified: true,
        avg_rating: 4.7,
        total_reviews: 78,
        total_bookings: 200,
        community_impact_score: 8.6,
        amenities: ["Clay materials", "Expert instruction", "Take-home pottery", "Traditional tea"],
        languages: ["Nepali", "English", "Newari"],
    },
    {
        id: "exp-010",
        title: "Lumbini Buddhist Pilgrimage Tour",
        slug: "lumbini-buddhist-pilgrimage",
        short_description: "Pilgrimage to Lumbini, the birthplace of Buddha, with guided monastery tours and meditation.",
        category: "heritage_site",
        price_per_person: 6000,
        currency: "NPR",
        duration_hours: 10,
        location_name: "Lumbini Sacred Garden",
        district: "Rupandehi",
        is_verified: true,
        avg_rating: 4.8,
        total_reviews: 145,
        total_bookings: 450,
        community_impact_score: 8.0,
        amenities: ["Expert Buddhist guide", "Meditation session", "Monastery visits", "Lunch", "Transport"],
        languages: ["Nepali", "English", "Hindi"],
    },
];

export const fallbackTrails = [
    {
        id: "trail-001",
        title: "Kathmandu Valley Heritage Circuit",
        slug: "kathmandu-heritage-circuit",
        description: "A 5-day deep dive into the art, architecture, and living culture of the Kathmandu Valley.",
        difficulty: "easy",
        duration_days: 5,
        total_cost_estimate: 25000,
        currency: "NPR",
        interests: ["Culture", "Food", "Spirituality"],
        travel_style: "Cultural Explorer",
        is_featured: true,
        total_bookings: 230,
        avg_rating: 4.8,
    },
    {
        id: "trail-002",
        title: "Annapurna Culture & Adventure Trail",
        slug: "annapurna-culture-adventure",
        description: "Combine breathtaking mountain scenery with authentic Gurung culture over 7 unforgettable days.",
        difficulty: "moderate",
        duration_days: 7,
        total_cost_estimate: 35000,
        currency: "NPR",
        interests: ["Trekking", "Culture", "Adventure"],
        travel_style: "Active Adventurer",
        is_featured: true,
        total_bookings: 180,
        avg_rating: 4.9,
    },
    {
        id: "trail-003",
        title: "Sacred Nepal Spiritual Journey",
        slug: "sacred-nepal-spiritual",
        description: "A soul-stirring 6-day pilgrimage across Nepal's most sacred sites from Lumbini to Kathmandu.",
        difficulty: "easy",
        duration_days: 6,
        total_cost_estimate: 30000,
        currency: "NPR",
        interests: ["Spirituality", "Culture"],
        travel_style: "Spiritual Seeker",
        is_featured: true,
        total_bookings: 150,
        avg_rating: 4.7,
    },
];

export const fallbackImpactStats = {
    families_supported: 1247,
    total_revenue_generated: 45200000,
    community_share_percentage: 72,
    cultural_programs_funded: 34,
    artisans_employed: 389,
    heritage_sites_maintained: 12,
    districts_reached: 28,
    travelers_served: 8940,
};

export const fallbackImpactDistribution = {
    categories: [
        { category: "Homestay Families", percentage: 35, amount: 15820000 },
        { category: "Local Guides", percentage: 25, amount: 11300000 },
        { category: "Artisan Workshops", percentage: 20, amount: 9040000 },
        { category: "Heritage Preservation", percentage: 12, amount: 5424000 },
        { category: "Community Education", percentage: 8, amount: 3616000 },
    ],
    regional: [
        { district: "Kaski", families: 280, revenue: 9800000 },
        { district: "Bhaktapur", families: 195, revenue: 7200000 },
        { district: "Solukhumbu", families: 165, revenue: 8500000 },
        { district: "Lalitpur", families: 150, revenue: 5400000 },
        { district: "Kathmandu", families: 180, revenue: 6300000 },
        { district: "Rasuwa", families: 95, revenue: 3200000 },
        { district: "Rupandehi", families: 82, revenue: 2800000 },
    ],
};
